shub/urls.py
"""

Copyright (C) 2017-2020 Vanessa Sochat.

This Source Code Form is subject to the terms of the
Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed
with this file, You can obtain one at http://mozilla.org/MPL/2.0/.

"""

from importlib import import_module

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap, index
from shub.apps.api import urls as api_urls
from shub.apps.base import urls as base_urls
from shub.apps.library import urls as library_urls
from shub.apps.main import urls as main_urls
from shub.apps.users import urls as user_urls
from shub.apps.base.sitemap import CollectionSitemap, ContainerSitemap

from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls

# Documentation URL
API_TITLE = "Singularity Registry API"
API_DESCRIPTION = "Open Source Container Registry API"
schema_view = get_schema_view(title=API_TITLE)

# Configure custom error pages
handler404 = "shub.apps.base.views.handler404"
handler500 = "shub.apps.base.views.handler500"

# Sitemaps
sitemaps = {"containers": ContainerSitemap, "collections": CollectionSitemap}

urlpatterns = [
    url(r"^admin/", admin.site.urls),
    url(r"^", include(base_urls)),
    url(r"^api/", include(api_urls)),
    url(r"^", include(library_urls)),  # Sylabs library API - includes v1 and v2 (damn)
    url(r"^api/schema/$", schema_view),
    url(r"^api/docs/", include_docs_urls(title=API_TITLE, description=API_DESCRIPTION)),
    url(r"^", include(main_urls)),
    url(r"^", include(user_urls)),
    url(r"^sitemap\.xml$", index, {"sitemaps": sitemaps}, name="sitemap"),
    url(r"^sitemap-(?P<section>.+)\.xml$", sitemap, {"sitemaps": sitemaps}),
    url(r"^django-rq/", include("django_rq.urls")),
]

# Load URLs for any enabled plugins
for plugin in settings.PLUGINS_ENABLED:
    urls_module = "shub.plugins." + plugin + ".urls"
    plugin_urls = import_module(urls_module)

    url_regex = "^" + plugin + "/"

    # per protocol, keystore must be /pks
    if plugin == "pgp":
        url_regex = "^pks/"
    urlpatterns.append(url(url_regex, include(plugin_urls)))

shub/apps/api/models/storage.py
"""

Copyright (C) 2017-2020 Vanessa Sochat.

This Source Code Form is subject to the terms of the
Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed
with this file, You can obtain one at http://mozilla.org/MPL/2.0/.

"""

from django.core.files.storage import FileSystemStorage
from django.conf import settings
import os

################################################################################
# STORAGE
################################################################################


class OverwriteStorage(FileSystemStorage):
    def get_available_name(self, name, max_length=None):
        # If the filename already exists, remove it as if it was a true file system
        if self.exists(name):
            os.remove(os.path.join(settings.MEDIA_ROOT, name))
        return name

shub/apps/users/models.py
"""

Copyright (C) 2017-2020 Vanessa Sochat.

This Source Code Form is subject to the terms of the
Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed
with this file, You can obtain one at http://mozilla.org/MPL/2.0/.

"""

from django.conf import settings
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver

from django.urls import reverse
from django.db import models

from rest_framework.authtoken.models import Token
from shub.apps.users.utils import get_usertoken
from itertools import chain
import os

################################################################################
# Supporting Functions
################################################################################


# Get path to where images are stored for teams
def get_image_path(instance, filename):
    team_folder = os.path.join(settings.MEDIA_ROOT, "teams")
    if not os.path.exists(team_folder):
        os.mkdir(team_folder)
    return os.path.join("teams", filename)


TEAM_TYPES = (
    ("invite", "Invite only. The user must be invited by an owner"),
    ("open", "Open. Anyone can join the team without asking."),
)


class CustomUserManager(BaseUserManager):
    def _create_user(
        self, username, email, password, is_staff, is_superuser, **extra_fields
    ):
        """
        Creates and saves a User with the given username, email and password.
        """
        if not username:
            raise ValueError("The given username must be set")

        email = self.normalize_email(email)
        user = self.model(
            username=username,
            email=email,
            is_staff=is_staff,
            is_active=True,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email=None, password=None, **extra_fields):
        return self._create_user(
            username, email, password, False, False, **extra_fields
        )

    def create_superuser(self, username, email, password, **extra_fields):
        return self._create_user(username, email, password, True, True, **extra_fields)

    def add_superuser(self, user):
        """ Intended for existing user"""
        user.is_superuser = True
        user.save(using=self._db)
        return user

    def add_staff(self, user):
        """ Intended for existing user"""
        user.is_staff = True
        user.save(using=self._db)
        return user


class User(AbstractUser):
    active = models.BooleanField(default=True)

    # has the user agreed to terms?
    agree_terms = models.BooleanField(default=False)
    agree_terms_date = models.DateTimeField(blank=True, default=None, null=True)

    # Ensure that we can add staff / superuser and retain on logout
    objects = CustomUserManager()

    class Meta:
        app_label = "users"

    def has_create_permission(self):
        """has create permission determines if the user (globally) can create
           new collections. By default, superusers and admin can, along with
           regular users if USER_COLLECTIONS is True. Otherwise, not.
        """
        if self.is_superuser is True or self.is_staff is True:
            return True
        if settings.USER_COLLECTIONS is True:
            return True
        return False

    def is_team_member(self, collection):
        """given a collection, determine if the user is member of any teams 
           associated with the collection
        """
        for owner in collection.owners.all():
            for team in owner.team_owners.all():
                if self in team.members.all():
                    return True
        return False

    def is_team_owner(self, collection):
        """given a collection, determine if the user is owner of any teams 
           associated with the collection
        """
        for owner in collection.owners.all():
            for team in owner.team_owners.all():
                if self in team.owners.all():
                    return True
        return False

    def get_credentials(self, provider):
        """ return one or more credentials, or None"""
        if self.is_anonymous is False:
            try:
                # Case 1: one credential
                credential = self.social_auth.get(provider=provider)
                return credential
            except:
                # Case 2: more than one credential for the provider
                credential = self.social_auth.filter(provider=provider)
                if credential:
                    return credential.last()

    def get_providers(self):
        """return a list of providers that the user has credentials for.
        """
        return [x.provider for x in self.social_auth.all()]

    def get_label(self):
        return "users"

    @property
    def token(self):
        return get_usertoken(self)


################################################################################
# Teams
################################################################################


class Team(models.Model):
    """A team is a group of users with shared affiliation. One or more owners
       can edit the team name, photo, etc. Each user can join one or more
       teams.
    """

    name = models.CharField(max_length=50, unique=True, default=None)

    owners = models.ManyToManyField(
        User,
        blank=True,
        default=None,
        related_name="team_owners",
        related_query_name="team_owners",
        help_text="Administrators of the team.",
    )

    members = models.ManyToManyField(
        User,
        blank=True,
        default=None,
        related_name="contributors",
        related_query_name="contributors",
        help_text="Contributors to the team.",
    )

    created_at = models.DateTimeField("date of creation", auto_now_add=True)
    updated_at = models.DateTimeField("date of last update", auto_now=True)

    permission = models.CharField(
        choices=TEAM_TYPES,
        default="invite",
        max_length=100,
        verbose_name="Permission needed to join team",
    )

    team_image = models.ImageField(upload_to=get_image_path, blank=True, null=True)

    def get_members(self):
        """ get a list of unique members, including both contributors and owners
        """
        members = chain(self.owners.all(), self.members.all())
        return list(set(list(members)))

    def get_invite(self, code):
        """ get the invitation for a user, if it exists.
 
            Parameters
            ==========
            code: the code to validate the invitation
        """
        keyargs = {"code": code, "team": self}
        try:
            invite = MembershipInvite.objects.get(**keyargs)
        except MembershipInvite.DoesNotExist:
            return None
        else:
            return invite

    def add_member(self, user, code=None):
        """add a user to a team. If a code is provided,
        the invitation object is deleted.

        Parameters 
        ==========
        user: the user to add as a member
        code: if provided, ensure valid, then delete

        """
        if code is not None:
            invitation = self.get_invite(code)
            if invitation is not None:
                invitation.delete()

        # Finally, add the user
        self.members.add(user)
        self.save()
        return self

    def has_edit_permission(self, request):
        """ determine if a user has edit permission for a team.

            1. A superuser has edit permission, always
            2. A global admin has edit permission, always
            3. A user has edit permission if is one of the owners

        """
        # Global edit permission for superuser and staff
        if request.user.is_superuser or request.user.is_staff:
            return True

        # Edit permission to owners given so
        elif request.user in self.owners.all():
            return True

        return False

    def get_absolute_url(self):
        return reverse("team_details", args=[str(self.id)])

    def has_member(self, username):
        """return True if the username is either a member or owner for the team
          
        Parameters
        ==========
        username: the username to check
        """
        members = self.get_members()
        names = [x.username for x in members]
        if username in names:
            return True
        return False

    def __str__(self):
        return "%s" % self.name

    def __unicode__(self):
        return "%s" % self.name

    def get_label(self):
        return "users"

    class Meta:
        app_label = "users"


class MembershipInvite(models.Model):
    """An invitation to join a team.
    """

    code = models.CharField(max_length=200, null=False, blank=False)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    def __str__(self):
        return "<%s:%s>" % (self.id, self.team.name)

    def __unicode__(self):
        return "<%s:%s>" % (self.id, self.team.name)

    def get_label(self):
        return "users"

    def get_url(self):
        """return the reverse, invitation link for the user to follow
        """
        return "%s%s" % (
            settings.DOMAIN_NAME,
            reverse("join_team", args=[self.team.id, self.code]),
        )

    class Meta:
        app_label = "users"
        unique_together = (("code", "team"),)


################################################################################
# Post Save
################################################################################


@receiver(pre_save, sender=Team)
def create_team_group(sender, instance, **kwargs):

    # Get the name from the team
    name = instance.name.replace(" ", "-").lower().strip()
    instance.name = name


@receiver(post_save, sender=settings.AUTH_USER_MODEL)

shub/plugins/google_build/models.py
"""

Copyright (C) 2019-2020 Vanessa Sochat.

This Source Code Form is subject to the terms of the
Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed
with this file, You can obtain one at http://mozilla.org/MPL/2.0/.

"""

from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from shub.apps.api.models.storage import OverwriteStorage
from .actions import trigger_build
import uuid
import os


def get_upload_folder(instance, filename):
    """a helper function to upload a recipe file to storage.
    """
    from shub.apps.main.models import Collection

    collection_name = instance.collection.lower()
    instance.collection = collection_name

    # First get a collection
    try:
        collection = Collection.objects.get(name=collection_name)
    except Collection.DoesNotExist:
        collection = Collection.objects.create(name=collection_name)
        collection.secret = str(uuid.uuid4())
        collection.save()

    # Create collection root, if it doesn't exist
    image_home = os.path.join(settings.MEDIA_ROOT, collection_name)
    recipe_home = os.path.join(image_home, "recipes")

    for dirname in [image_home, recipe_home]:
        if not os.path.exists(dirname):
            os.mkdir(dirname)

    return os.path.join(recipe_home, filename)


class RecipeFile(models.Model):
    """a RecipeFile is a Singularity Recipe pushed to do a remote build.
    """

    created = models.DateTimeField(auto_now_add=True)
    collection = models.CharField(max_length=200, null=False)
    tag = models.CharField(max_length=200, null=False)
    name = models.CharField(max_length=200, null=False)
    owner_id = models.CharField(max_length=200, null=True)
    datafile = models.FileField(
        upload_to=get_upload_folder, max_length=255, storage=OverwriteStorage()
    )

    def get_label(self):
        return "recipefile"

    def __str__(self):
        if hasattr(self.datafile, "name"):
            return self.datafile.name
        return self.get_label()

    def get_abspath(self):
        return os.path.join(settings.MEDIA_ROOT, self.datafile.name)

    class Meta:
        app_label = "api"


# Trigger a build when a recipe is uploaded
post_save.connect(trigger_build, sender=RecipeFile)

shub/apps/api/templates/routes/api.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% block head %}
{% endblock %}
{% block content %}

        <div id="fh5co-team">
            <div class="container">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <div class="row">
                            <h2 class="section-lead text-center">API</h2>
                            <p class="text-center">Application Programming Interface (under development)</p>

                            <em>The Singularity Hub RESTful API</em> provides programmatic access to public containers. You can use this interface to explore the data, and we recommend our command line client for deploying containers (under development).</p>

                            <div class="panes">
                                <div class="pane">
                                    <div>
                                        <strong>Sitemap</strong> <a href="{% url 'sitemap' %}" target="_blank">{{ domain }}/sitemap.xml</a><br>
                                        <strong>Containers</strong> <a href="/api/containers" target="_blank">{{ domain }}/api/containers</a><br>
                                        <strong>Collections</strong> <a href="/api/collections" target="_blank">{{ domain }}/api/collections</a><br>
                                    </div>
                                </div> 
                            </div>
                        </div>     
                    </div>
                </div>
            </div>
        </div>

{% endblock %}

shub/apps/api/templates/routes/loading.html
<style>
#loading {
    position:absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: #ffffff;
    z-index: 2001;
    -moz-opacity: 0.9;
    opacity: 0.9;
    filter: alpha(opacity=90);
}
.dots {
  width: 0;
  height: 0;
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  margin: auto;
  -webkit-filter: url(#goo);
          filter: url(#goo);
}

.dot {
  width: 0;
  height: 0;
  position: absolute;
  left: 0;
  top: 0;
}
.dot:before {
  content: '';
  width: 35px;
  height: 35px;
  border-radius: 50px;
  background: #FBD301;
  position: absolute;
  left: 50%;
  -webkit-transform: translateY(0) rotate(0deg);
          transform: translateY(0) rotate(0deg);
  margin-left: -17.5px;
  margin-top: -17.5px;
}
@-webkit-keyframes dot-move {
  0% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
  }
  18%, 22% {
    -webkit-transform: translateY(-70px);
            transform: translateY(-70px);
  }
  40%, 100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
  }
}
@keyframes dot-move {
  0% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
  }
  18%, 22% {
    -webkit-transform: translateY(-70px);
            transform: translateY(-70px);
  }
  40%, 100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
  }
}
@-webkit-keyframes dot-colors {
  0% {
    background-color: #FBD301;
  }
  25% {
    background-color: #FF3270;
  }
  50% {
    background-color: #208BF1;
  }
  75% {
    background-color: #AFE102;
  }
  100% {
    background-color: #FBD301;
  }
}
@keyframes dot-colors {
  0% {
    background-color: #FBD301;
  }
  25% {
    background-color: #FF3270;
  }
  50% {
    background-color: #208BF1;
  }
  75% {
    background-color: #AFE102;
  }
  100% {
    background-color: #FBD301;
  }
}
.dot:nth-child(5):before {
  z-index: 100;
  width: 45.5px;
  height: 45.5px;
  margin-left: -22.75px;
  margin-top: -22.75px;
  -webkit-animation: dot-colors 4s ease infinite;
          animation: dot-colors 4s ease infinite;
}
@-webkit-keyframes dot-rotate-1 {
  0% {
    -webkit-transform: rotate(-105deg);
            transform: rotate(-105deg);
  }
  100% {
    -webkit-transform: rotate(270deg);
            transform: rotate(270deg);
  }
}
@keyframes dot-rotate-1 {
  0% {
    -webkit-transform: rotate(-105deg);
            transform: rotate(-105deg);
  }
  100% {
    -webkit-transform: rotate(270deg);
            transform: rotate(270deg);
  }
}
.dot:nth-child(1) {
  -webkit-animation: dot-rotate-1 4s 0s linear infinite;
          animation: dot-rotate-1 4s 0s linear infinite;
}
.dot:nth-child(1):before {
  background-color: #FF3270;
  -webkit-animation: dot-move 4s 0s ease infinite;
          animation: dot-move 4s 0s ease infinite;
}
@-webkit-keyframes dot-rotate-2 {
  0% {
    -webkit-transform: rotate(165deg);
            transform: rotate(165deg);
  }
  100% {
    -webkit-transform: rotate(540deg);
            transform: rotate(540deg);
  }
}
@keyframes dot-rotate-2 {
  0% {
    -webkit-transform: rotate(165deg);
            transform: rotate(165deg);
  }
  100% {
    -webkit-transform: rotate(540deg);
            transform: rotate(540deg);
  }
}
.dot:nth-child(2) {
  -webkit-animation: dot-rotate-2 4s 1s linear infinite;
          animation: dot-rotate-2 4s 1s linear infinite;
}
.dot:nth-child(2):before {
  background-color: #208BF1;
  -webkit-animation: dot-move 4s 1s ease infinite;
          animation: dot-move 4s 1s ease infinite;
}
@-webkit-keyframes dot-rotate-3 {
  0% {
    -webkit-transform: rotate(435deg);
            transform: rotate(435deg);
  }
  100% {
    -webkit-transform: rotate(810deg);
            transform: rotate(810deg);
  }
}
@keyframes dot-rotate-3 {
  0% {
    -webkit-transform: rotate(435deg);
            transform: rotate(435deg);
  }
  100% {
    -webkit-transform: rotate(810deg);
            transform: rotate(810deg);
  }
}
.dot:nth-child(3) {
  -webkit-animation: dot-rotate-3 4s 2s linear infinite;
          animation: dot-rotate-3 4s 2s linear infinite;
}
.dot:nth-child(3):before {
  background-color: #AFE102;
  -webkit-animation: dot-move 4s 2s ease infinite;
          animation: dot-move 4s 2s ease infinite;
}
@-webkit-keyframes dot-rotate-4 {
  0% {
    -webkit-transform: rotate(705deg);
            transform: rotate(705deg);
  }
  100% {
    -webkit-transform: rotate(1080deg);
            transform: rotate(1080deg);
  }
}
@keyframes dot-rotate-4 {
  0% {
    -webkit-transform: rotate(705deg);
            transform: rotate(705deg);
  }
  100% {
    -webkit-transform: rotate(1080deg);
            transform: rotate(1080deg);
  }
}
.dot:nth-child(4) {
  -webkit-animation: dot-rotate-4 4s 3s linear infinite;
          animation: dot-rotate-4 4s 3s linear infinite;
}
.dot:nth-child(4):before {
  background-color: #FBD301;
  -webkit-animation: dot-move 4s 3s ease infinite;
          animation: dot-move 4s 3s ease infinite;
}
</style>
<div id="loading">
    <div class="dots">
        <div class="dot"></div>
        <div class="dot"></div>
        <div class="dot"></div>
        <div class="dot"></div>
        <div class="dot"></div>
    </div>

<svg xmlns="http://www.w3.org/2000/svg" version="1.1">
  <defs>
    <filter id="goo">
      <feGaussianBlur in="SourceGraphic" stdDeviation="12" result="blur" />
      <feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -7" result="goo" />
      <feBlend in="SourceGraphic" in2="goo" />
    </filter>
  </defs>
</svg>
</div>
<script>
var $loading = $('#loading').hide();
$(document)
  // Show loading when any ajax starts
  .ajaxStart(function () {
    $loading.show();
  })
  .ajaxStop(function () {
    $loading.hide();
  });
  // Also show when a form is submit
  $('form').submit(function() {
    $loading.show();    
    return true;
  });
</script>

shub/apps/api/templates/routes/upload.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% block head %}

{% endblock %}
{% block content %}

  <h2 class="title">
    Upload to <span style="color:#d61c1c">{{ collection.name }}
  </h2>

    <form name="upload" method="POST" enctype="multipart/form-data" action="/upload">
      {% csrf_token %}
      <input type="file" name="file1" required><br>
  <div id="div_id_name" class="form-group" style='width:400px'>
      <label for="id_name" 
             class="control-label  requiredField">Container Name<span class="asteriskField">*</span></label>
           <div class="controls">
           <input type="text" 
             name="name" 
             value=""
             placeholder="ubuntu" 
             required=""
             maxlength="50" class="textinput textInput form-control"  
             id="id_name">      
             </div>
      </div>
  <div id="div_id_tag" class="form-group" style='width:400px'>
      <label for="id_name" 
             class="control-label  requiredField">Container Tag<span class="asteriskField">*</span></label>
      <div class="controls">
      <input type="text" 
             name="tag" 
             value=""
             placeholder="latest" 
             required=""
             maxlength="50" class="textinput textInput form-control"  
             id="id_tag">      
      </div>
  </div>
      <input type="submit" class="btn btn-primary" name="submit" value="Upload">
      <input type="hidden" name="collection" value="{{ cid }}">
    </form>

  <div id="messages"></div>

{% endblock %}